unit unt_print_haml_bar_tarikh;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls;

type
  TFrm_print_haml_bar_tarikh = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape18: TQRShape;
    QRSysData1: TQRSysData;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel6: TQRLabel;
    QRShape7: TQRShape;
    QRShape5: TQRShape;
    QRLabel10: TQRLabel;
    QRShape27: TQRShape;
    QRLabel8: TQRLabel;
    QRLabel20: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel24: TQRLabel;
    QRShape1: TQRShape;
    QRShape24: TQRShape;
    QRL_type: TQRLabel;
    QRBand1: TQRBand;
    QRDBText18: TQRDBText;
    QRExpr2: TQRExpr;
    QRShape12: TQRShape;
    QRShape16: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRDBText1: TQRDBText;
    QRShape26: TQRShape;
    QRDBText8: TQRDBText;
    QRBand2: TQRBand;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel29: TQRLabel;
    QRDBText2: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText20: TQRDBText;
    QRShape34: TQRShape;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Frm_print_haml_bar_tarikh: TFrm_print_haml_bar_tarikh;

implementation

uses unt_DataM_forosh;

{$R *.dfm}

end.
