unit unt_print_gozaresh_ranande_daron;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls;

type
  Tfrm_print_gozaresh_ranande_daron = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape18: TQRShape;
    QRSysData1: TQRSysData;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel6: TQRLabel;
    QRShape7: TQRShape;
    QRShape5: TQRShape;
    QRLabel10: TQRLabel;
    QRLabel8: TQRLabel;
    QRShape1: TQRShape;
    QRShape24: TQRShape;
    QRL_type: TQRLabel;
    QRShape2: TQRShape;
    QRLabel2: TQRLabel;
    QRBand1: TQRBand;
    QRDBText18: TQRDBText;
    QRExpr2: TQRExpr;
    QRShape12: TQRShape;
    QRShape16: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRDBText1: TQRDBText;
    QRShape3: TQRShape;
    QRDBText6: TQRDBText;
    QRBand2: TQRBand;
    QRShape4: TQRShape;
    QRShape6: TQRShape;
    QRShape8: TQRShape;
    QRLabel29: TQRLabel;
    QRDBText12: TQRDBText;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frm_print_gozaresh_ranande_daron: Tfrm_print_gozaresh_ranande_daron;

implementation

uses unt_gozaresh, unt_Datam_gozaresh;

{$R *.dfm}

end.
