unit unt_print_factor_bedeh_talab2;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls;

type
  Tfrm_print_factor_bedeh_talab2 = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel2: TQRLabel;
    QRShape7: TQRShape;
    QRLabel9: TQRLabel;
    QRShape1: TQRShape;
    QRShape24: TQRShape;
    QRShape5: TQRShape;
    QRLabel7: TQRLabel;
    QRShape2: TQRShape;
    QRLabel12: TQRLabel;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRLabel14: TQRLabel;
    QRDBText10: TQRDBText;
    QRShape28: TQRShape;
    QRLabel1: TQRLabel;
    QRSysData1: TQRSysData;
    QRLabel13: TQRLabel;
    QRLabel10: TQRLabel;
    QRBand1: TQRBand;
    QRExpr2: TQRExpr;
    QRShape16: TQRShape;
    QRShape23: TQRShape;
    QRShape31: TQRShape;
    QRDBText2: TQRDBText;
    QRShape4: TQRShape;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRShape22: TQRShape;
    QRShape29: TQRShape;
    QRDBText1: TQRDBText;
    QRBand2: TQRBand;
    QRShape6: TQRShape;
    QRShape8: TQRShape;
    QRLabel3: TQRLabel;
    QRShape19: TQRShape;
    QRDBText19: TQRDBText;
    QRShape25: TQRShape;
    QRDBText3: TQRDBText;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRShape9: TQRShape;
    QRL_gabl_natije: TQRLabel;
    QRShape3: TQRShape;
    QRL_kol: TQRLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frm_print_factor_bedeh_talab2: Tfrm_print_factor_bedeh_talab2;

implementation

uses unt_DataM_final;
{$R *.dfm}

end.
