unit UNT_PRINT_BARAYE_KHARIDAR;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls;

type
  TFRM_PRINT_BARAYE_KHARIDAR = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel2: TQRLabel;
    QRShape7: TQRShape;
    QRLabel10: TQRLabel;
    QRShape27: TQRShape;
    QRLabel9: TQRLabel;
    QRShape1: TQRShape;
    QRShape24: TQRShape;
    QRShape5: TQRShape;
    QRShape17: TQRShape;
    QRLabel6: TQRLabel;
    QRBand1: TQRBand;
    QRDBText13: TQRDBText;
    QRExpr2: TQRExpr;
    QRShape16: TQRShape;
    QRShape23: TQRShape;
    QRShape31: TQRShape;
    QRDBText1: TQRDBText;
    QRDBText2: TQRDBText;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape18: TQRShape;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRBand2: TQRBand;
    QRShape6: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRShape12: TQRShape;
    QRLabel3: TQRLabel;
    QRShape15: TQRShape;
    QRShape21: TQRShape;
    QRLabel5: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel11: TQRLabel;
    QRShape2: TQRShape;
    QRShape22: TQRShape;
    QRShape25: TQRShape;
    QRLabel12: TQRLabel;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRLabel14: TQRLabel;
    QRDBText10: TQRDBText;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRLabel15: TQRLabel;
    QRLabel16: TQRLabel;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape19: TQRShape;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRDBText16: TQRDBText;
    QRLabel1: TQRLabel;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText12: TQRDBText;
    QRDBText17: TQRDBText;
    QRDBText18: TQRDBText;
    QRDBText19: TQRDBText;
    QRSysData1: TQRSysData;
    QRLabel13: TQRLabel;
    QRShape20: TQRShape;
    QRLabel17: TQRLabel;
    QRDBText9: TQRDBText;
    QRL_type: TQRLabel;
    QRLabel4: TQRLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FRM_PRINT_BARAYE_KHARIDAR: TFRM_PRINT_BARAYE_KHARIDAR;

implementation

uses unt__forosh, unt_DataM_forosh, unt_DataM_group_by;

{$R *.dfm}

end.
