unit unt_print_bank2;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls;

type
  TFrm_print_bank2 = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape18: TQRShape;
    QRSysData1: TQRSysData;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel7: TQRLabel;
    QRShape7: TQRShape;
    QRShape4: TQRShape;
    QRShape6: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRLabel13: TQRLabel;
    QRLabel16: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRShape28: TQRShape;
    QRLabel9: TQRLabel;
    QRShape1: TQRShape;
    QRShape24: TQRShape;
    QRL_type: TQRLabel;
    QRLabel6: TQRLabel;
    QRBand1: TQRBand;
    QRDBText16: TQRDBText;
    QRDBText18: TQRDBText;
    QRDBText19: TQRDBText;
    QRDBText22: TQRDBText;
    QRExpr2: TQRExpr;
    QRShape12: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRDBText3: TQRDBText;
    QRBand2: TQRBand;
    QRDBText10: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText20: TQRDBText;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape34: TQRShape;
    QRShape5: TQRShape;
    QRShape10: TQRShape;
    QRDBText1: TQRDBText;
    QRLabel8: TQRLabel;
    QRShape11: TQRShape;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Frm_print_bank2: TFrm_print_bank2;

implementation

uses unt_DataM_final;

{$R *.dfm}

end.
