unit unt_print_talabkaran;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls;

type
  Tfrm_print_talabkaran = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRL_type: TQRLabel;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel1: TQRLabel;
    QRShape7: TQRShape;
    QRLabel10: TQRLabel;
    QRShape27: TQRShape;
    QRLabel9: TQRLabel;
    QRShape1: TQRShape;
    QRShape24: TQRShape;
    QRShape5: TQRShape;
    QRShape17: TQRShape;
    QRLabel5: TQRLabel;
    QRShape19: TQRShape;
    QRLabel6: TQRLabel;
    QRLabel13: TQRLabel;
    QRSysData1: TQRSysData;
    QRBand1: TQRBand;
    QRExpr2: TQRExpr;
    QRShape16: TQRShape;
    QRShape23: TQRShape;
    QRShape31: TQRShape;
    QRDBText2: TQRDBText;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape18: TQRShape;
    QRDBText5: TQRDBText;
    QRShape20: TQRShape;
    QRDBText6: TQRDBText;
    QRBand2: TQRBand;
    QRShape6: TQRShape;
    QRShape8: TQRShape;
    QRShape9: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRLabel3: TQRLabel;
    QRDBText4: TQRDBText;
    QRLabel2: TQRLabel;
    QRDBText3: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText1: TQRDBText;
    QRShape2: TQRShape;
    QRShape22: TQRShape;
    QRLabel4: TQRLabel;
    qrl_sodor_factor: TQRLabel;
    QRSysData2: TQRSysData;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frm_print_talabkaran: Tfrm_print_talabkaran;

implementation

uses unt_DataM_final, unt_DataM_forosh;

{$R *.dfm}

end.
