unit unt_print_pardakht_be_foroshande_jam;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, QRCtrls, QuickRpt, ExtCtrls;

type
  Tfrm_print_pardakht_be_foroshande_jam = class(TForm)
    QuickRep1: TQuickRep;
    TitleBand1: TQRBand;
    QRShape18: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape24: TQRShape;
    QRL_type: TQRLabel;
    QRBand1: TQRBand;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRDBText2: TQRDBText;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRDBText3: TQRDBText;
    QRLabel4: TQRLabel;
    QRDBText4: TQRDBText;
    QRLabel5: TQRLabel;
    QRDBText5: TQRDBText;
    QRLabel6: TQRLabel;
    QRDBText6: TQRDBText;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel7: TQRLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frm_print_pardakht_be_foroshande_jam: Tfrm_print_pardakht_be_foroshande_jam;

implementation

{$R *.dfm}

end.
